#pragma once
#define MAJOR_VERSION "1"
#define MINOR_VERSION "0"
#define REVISION_VERSION "0"
#define BUILD_NUMBER "2"
#define FULL_VERSION MAJOR_VERSION "." MINOR_VERSION "." REVISION_VERSION "." BUILD_NUMBER
