#pragma once
#define MAJOR_VERSION "1"
#define MINOR_VERSION "1"
#define REVISION_VERSION "1"
#define BUILD_NUMBER "0"
#define FULL_VERSION MAJOR_VERSION "." MINOR_VERSION "." REVISION_VERSION "." BUILD_NUMBER
